### ISSUE TITLE
Build Chapters Page

### ISSUE THREAD

**Issue by AsirAAlam** [OffTheBattlefieldFoundation/obf-web#2]
Deliverables:
- Build the Chapters page
- Cards for each chapter
- Click on a chapter to open it
- Button to submit request for a new chapter -> redirects to google form

![image](https://github.com/user-attachments/assets/f4087f41-dcd5-4e5e-b158-ed63e84c78a4)

**Comment by GoodMishka** [comment]
"Start Your Own Chapter!" Google Form: https://forms.gle/mfcgdmbGD4m51U9k7
